- name: Setup Nodes
  hosts: loadbalancer
  become: yes
  tasks:
    - name: Disable UFW (Uncomplicated Firewall)
      ufw:
        state: disabled

    - name: Disable swap on all nodes
      shell: |
        swapoff -a
        sed -i '/swap/d' /etc/fstab

- name: Setup Load Balancer
  hosts: loadbalancer
  become: yes
  tasks:
    - name: Ensure /etc/keepalived directory exists
      file:
        path: /etc/keepalived
        state: directory
        mode: "0755"

    - name: Ensure /etc/haproxy directory exists
      file:
        path: /etc/haproxy
        state: directory
        mode: "0755"

    - name: Create check_apiserver.sh script
      copy:
        dest: /etc/keepalived/check_apiserver.sh
        content: |
          #!/bin/sh
          errorExit() {
            echo "*** $@" 1>&2
            exit 1
          }
          curl --silent --max-time 2 --insecure https://localhost:6443/ -o /dev/null || errorExit "Error GET https://localhost:6443/"
          if ip addr | grep -q 192.168.31.147; then
            curl --silent --max-time 2 --insecure https://192.168.31.147:6443/ -o /dev/null || errorExit "Error GET https://192.168.31.147:6443/"
          fi

    - name: Make the check_apiserver.sh script executable
      file:
        path: /etc/keepalived/check_apiserver.sh
        mode: "0755"
        owner: root
        group: root

    - name: Create keepalived.conf configuration file
      copy:
        dest: /etc/keepalived/keepalived.conf
        content: |
          vrrp_script check_apiserver {
            script "/etc/keepalived/check_apiserver.sh"
            interval 3
            timeout 10
            fall 5
            rise 2
            weight -2
          }

          vrrp_instance VI_1 {
            state BACKUP
            interface ens33
            virtual_router_id 1
            priority 100
            advert_int 5
            authentication {
                auth_type PASS
                auth_pass mysecret
            }
            virtual_ipaddress {
                192.168.31.147
            }
            track_script {
                check_apiserver
            }
          }

    - name: Ensure correct permissions for keepalived.conf
      file:
        path: /etc/keepalived/keepalived.conf
        mode: "0644"
        owner: root
        group: root

    - name: Create haproxy.cfg configuration file
      copy:
        dest: /etc/haproxy/haproxy.cfg
        content: |
          frontend kubernetes-frontend
            bind *:6443
            mode tcp
            option tcplog
            default_backend kubernetes-backend

          backend kubernetes-backend
            option httpchk GET /healthz
            http-check expect status 200
            mode tcp
            option ssl-hello-chk
            balance roundrobin
            server master1 192.168.31.142:6443 check fall 3 rise 2

    - name: Ensure correct permissions for haproxy.cfg
      file:
        path: /etc/haproxy/haproxy.cfg
        mode: "0644"
        owner: root
        group: root

    - name: Create lb-setup.sh script to run the setup commands
      copy:
        dest: /usr/local/bin/lb-setup.sh
        content: |
          #!/bin/sh
          apt update && apt install -y keepalived haproxy
          systemctl enable --now keepalived
          systemctl enable haproxy && systemctl restart haproxy
        mode: "0755"

    - name: Run the lb-setup.sh script
      command: /usr/local/bin/lb-setup.sh
